
[re2]

language = "c++"


header_paths = [
    "database/re2/latest/code/re2/re2.h",
    "database/re2/latest/code/re2/set.h",
    "database/re2/latest/code/re2/filtered_re2.h",
    "database/re2/latest/code/re2/stringpiece.h",
]


compile_commands_path = "database/re2/latest/build_asan/compile_commands.json"


document_paths = ["database/re2/latest/code/README"]


document_has_api_usage = false


output_path = "database/re2/latest/out"

# [MODIFY THIS] The compile arguments while building the fuzz driver. The fuzz driver will be built using command like:
# clang++ path/to/fuzz/driver.cpp -o path/to/output -fsanitize=fuzzer,address,undefined -Ipath/to/headers [configured build args]
driver_build_args = [
    "database/re2/latest/bin_asan/lib/libre2.a",
    "-Idatabase/re2/latest/code",
    "-Idatabase/re2/abseil-cpp/bin/include",
    "-Ldatabase/re2/abseil-cpp/bin/lib",
    "-labsl_log_internal_check_op",
    "-labsl_leak_check",
    "-labsl_log_internal_conditions",
    "-labsl_log_internal_message",
    "-labsl_examine_stack",
    "-labsl_log_internal_format",
    "-labsl_log_internal_nullguard",
    "-labsl_log_internal_structured_proto",
    "-labsl_log_internal_proto",
    "-labsl_log_internal_log_sink_set",
    "-labsl_log_internal_globals",
    "-labsl_log_globals",
    "-labsl_log_sink",
    "-labsl_strerror",
    "-labsl_vlog_config_internal",
    "-labsl_log_internal_fnmatch",
    "-labsl_flags_internal",
    "-labsl_flags_marshalling",
    "-labsl_flags_reflection",
    "-labsl_flags_private_handle_accessor",
    "-labsl_flags_commandlineflag",
    "-labsl_flags_commandlineflag_internal",
    "-labsl_flags_config",
    "-labsl_flags_program_name",
    "-labsl_raw_hash_set",
    "-labsl_cord",
    "-labsl_cordz_info",
    "-labsl_cord_internal",
    "-labsl_cordz_functions",
    "-labsl_cordz_handle",
    "-labsl_crc_cord_state",
    "-labsl_crc32c",
    "-labsl_crc_internal",
    "-labsl_crc_cpu_detect",
    "-labsl_hashtablez_sampler",
    "-labsl_exponential_biased",
    "-labsl_hash",
    "-labsl_city",
    "-labsl_low_level_hash",
    "-labsl_str_format_internal",
    "-labsl_synchronization",
    "-labsl_graphcycles_internal",
    "-labsl_kernel_timeout_internal",
    "-labsl_stacktrace",
    "-labsl_symbolize",
    "-labsl_debugging_internal",
    "-labsl_demangle_internal",
    "-labsl_demangle_rust",
    "-labsl_decode_rust_punycode",
    "-labsl_utf8_for_code_point",
    "-labsl_malloc_internal",
    "-labsl_time",
    "-labsl_civil_time",
    "-labsl_strings",
    "-labsl_strings_internal",
    "-labsl_string_view",
    "-labsl_int128",
    "-labsl_throw_delegate",
    "-labsl_time_zone",
    "-labsl_tracing_internal",
    "-labsl_base",
    "-lrt",
    "-labsl_raw_logging_internal",
    "-labsl_log_severity",
    "-labsl_spinlock_wait"
]


exclude_paths = []


driver_headers = []

consumer_case_paths = [
    "database/re2/latest/code/re2/testing",
    "database/re2/latest/code/re2/fuzzing",
]

consumer_build_args = [
    "-Idatabase/re2/abseil-cpp/bin/include",
    "-Idatabase/re2/latest/code",
]

api_ban_list_path = "database/re2/api_ban_list.json"