[libjpeg-turbo]
language = "c"
compile_commands_path = "database/libjpeg-turbo/latest/build_asan/compile_commands.json"
document_paths = [
    "database/libjpeg-turbo/latest/code/README.md",
    "https://rawcdn.githack.com/libjpeg-turbo/libjpeg-turbo/main/doc/turbojpeg/group___turbo_j_p_e_g.html",
]
document_has_api_usage = true
output_path = "database/libjpeg-turbo/latest/out"
header_paths = ["database/libjpeg-turbo/latest/code/src/turbojpeg.h"]
driver_build_args = [
    "database/libjpeg-turbo/latest/bin_asan/lib/libturbojpeg.a",
    "-Idatabase/libjpeg-turbo/latest/build_asan",
]
consumer_case_paths = ["database/libjpeg-turbo/latest/code/fuzz"]
