# ======================== Configuration for svgpp ========================


[svgpp]

language = "c++"

compile_commands_path = "database/svgpp/latest/build_asan/compile_commands.json"


header_paths = ["database/svgpp/latest/code/include/svgpp"]


document_paths = ["database/svgpp/latest/code/doc/sphinx/_build/text"]


document_has_api_usage = true


output_path = "database/svgpp/latest/out"


driver_build_args = []


source_paths = []


exclude_paths = []


driver_headers = []


api_hints_path = ""

consumer_case_paths = [
    "database/svgpp/latest/code/src/test",
    "database/svgpp/latest/code/src/samples"
]
