[cares]
language = "c"
compile_commands_path = "database/c-ares/latest/build_asan/compile_commands.json"
document_paths = [
    "https://c-ares.org/",
    "https://c-ares.org/docs/ares_cancel.html",
    "https://c-ares.org/docs/ares_create_query.html",
    "https://c-ares.org/docs/ares_destroy.html",
    "https://c-ares.org/docs/ares_destroy_options.html",
    "https://c-ares.org/docs/ares_dns_class_fromstr.html",
    "https://c-ares.org/docs/ares_dns_class_t.html",
    "https://c-ares.org/docs/ares_dns_class_tostr.html",
    "https://c-ares.org/docs/ares_dns_datatype_t.html",
    "https://c-ares.org/docs/ares_dns_flags_t.html",
    "https://c-ares.org/docs/ares_dns_mapping.html",
    "https://c-ares.org/docs/ares_dns_opcode_t.html",
    "https://c-ares.org/docs/ares_dns_opcode_tostr.html",
    "https://c-ares.org/docs/ares_dns_opt_datatype_t.html",
    "https://c-ares.org/docs/ares_dns_opt_get_datatype.html",
    "https://c-ares.org/docs/ares_dns_opt_get_name.html",
    "https://c-ares.org/docs/ares_dns_parse.html",
    "https://c-ares.org/docs/ares_dns_rcode_t.html",
    "https://c-ares.org/docs/ares_dns_rcode_tostr.html",
    "https://c-ares.org/docs/ares_dns_rec_type_fromstr.html",
    "https://c-ares.org/docs/ares_dns_rec_type_t.html",
    "https://c-ares.org/docs/ares_dns_rec_type_tostr.html",
    "https://c-ares.org/docs/ares_dns_record.html",
    "https://c-ares.org/docs/ares_dns_record_create.html",
    "https://c-ares.org/docs/ares_dns_record_destroy.html",
    "https://c-ares.org/docs/ares_dns_record_duplicate.html",
    "https://c-ares.org/docs/ares_dns_record_get_flags.html",
    "https://c-ares.org/docs/ares_dns_record_get_id.html",
    "https://c-ares.org/docs/ares_dns_record_get_opcode.html",
    "https://c-ares.org/docs/ares_dns_record_get_rcode.html",
    "https://c-ares.org/docs/ares_dns_record_query_add.html",
    "https://c-ares.org/docs/ares_dns_record_query_cnt.html",
    "https://c-ares.org/docs/ares_dns_record_query_get.html",
    "https://c-ares.org/docs/ares_dns_record_query_set_name.html",
    "https://c-ares.org/docs/ares_dns_record_query_set_type.html",
    "https://c-ares.org/docs/ares_dns_record_rr_add.html",
    "https://c-ares.org/docs/ares_dns_record_rr_cnt.html",
    "https://c-ares.org/docs/ares_dns_record_rr_del.html",
    "https://c-ares.org/docs/ares_dns_record_rr_get.html",
    "https://c-ares.org/docs/ares_dns_record_rr_get_const.html",
    "https://c-ares.org/docs/ares_dns_record_set_id.html",
    "https://c-ares.org/docs/ares_dns_rr.html",
    "https://c-ares.org/docs/ares_dns_rr_add_abin.html",
    "https://c-ares.org/docs/ares_dns_rr_del_abin.html",
    "https://c-ares.org/docs/ares_dns_rr_del_opt_byid.html",
    "https://c-ares.org/docs/ares_dns_rr_get_abin.html",
    "https://c-ares.org/docs/ares_dns_rr_get_abin_cnt.html",
    "https://c-ares.org/docs/ares_dns_rr_get_addr.html",
    "https://c-ares.org/docs/ares_dns_rr_get_addr6.html",
    "https://c-ares.org/docs/ares_dns_rr_get_bin.html",
    "https://c-ares.org/docs/ares_dns_rr_get_class.html",
    "https://c-ares.org/docs/ares_dns_rr_get_keys.html",
    "https://c-ares.org/docs/ares_dns_rr_get_name.html",
    "https://c-ares.org/docs/ares_dns_rr_get_opt.html",
    "https://c-ares.org/docs/ares_dns_rr_get_opt_byid.html",
    "https://c-ares.org/docs/ares_dns_rr_get_opt_cnt.html",
    "https://c-ares.org/docs/ares_dns_rr_get_str.html",
    "https://c-ares.org/docs/ares_dns_rr_get_ttl.html",
    "https://c-ares.org/docs/ares_dns_rr_get_type.html",
    "https://c-ares.org/docs/ares_dns_rr_get_u16.html",
    "https://c-ares.org/docs/ares_dns_rr_get_u32.html",
    "https://c-ares.org/docs/ares_dns_rr_get_u8.html",
    "https://c-ares.org/docs/ares_dns_rr_key_datatype.html",
    "https://c-ares.org/docs/ares_dns_rr_key_t.html",
    "https://c-ares.org/docs/ares_dns_rr_key_to_rec_type.html",
    "https://c-ares.org/docs/ares_dns_rr_key_tostr.html",
    "https://c-ares.org/docs/ares_dns_rr_set_addr.html",
    "https://c-ares.org/docs/ares_dns_rr_set_addr6.html",
    "https://c-ares.org/docs/ares_dns_rr_set_bin.html",
    "https://c-ares.org/docs/ares_dns_rr_set_opt.html",
    "https://c-ares.org/docs/ares_dns_rr_set_str.html",
    "https://c-ares.org/docs/ares_dns_rr_set_u16.html",
    "https://c-ares.org/docs/ares_dns_rr_set_u32.html",
    "https://c-ares.org/docs/ares_dns_rr_set_u8.html",
    "https://c-ares.org/docs/ares_dns_section_t.html",
    "https://c-ares.org/docs/ares_dns_section_tostr.html",
    "https://c-ares.org/docs/ares_dns_write.html",
    "https://c-ares.org/docs/ares_dup.html",
    "https://c-ares.org/docs/ares_expand_name.html",
    "https://c-ares.org/docs/ares_expand_string.html",
    "https://c-ares.org/docs/ares_fds.html",
    "https://c-ares.org/docs/ares_free_data.html",
    "https://c-ares.org/docs/ares_free_hostent.html",
    "https://c-ares.org/docs/ares_free_string.html",
    "https://c-ares.org/docs/ares_freeaddrinfo.html",
    "https://c-ares.org/docs/ares_get_servers.html",
    "https://c-ares.org/docs/ares_get_servers_csv.html",
    "https://c-ares.org/docs/ares_get_servers_ports.html",
    "https://c-ares.org/docs/ares_getaddrinfo.html",
    "https://c-ares.org/docs/ares_gethostbyaddr.html",
    "https://c-ares.org/docs/ares_gethostbyname.html",
    "https://c-ares.org/docs/ares_gethostbyname_file.html",
    "https://c-ares.org/docs/ares_getnameinfo.html",
    "https://c-ares.org/docs/ares_getsock.html",
    "https://c-ares.org/docs/ares_inet_ntop.html",
    "https://c-ares.org/docs/ares_inet_pton.html",
    "https://c-ares.org/docs/ares_init.html",
    "https://c-ares.org/docs/ares_init_options.html",
    "https://c-ares.org/docs/ares_library_cleanup.html",
    "https://c-ares.org/docs/ares_library_init.html",
    "https://c-ares.org/docs/ares_library_init_android.html",
    "https://c-ares.org/docs/ares_library_initialized.html",
    "https://c-ares.org/docs/ares_mkquery.html",
    "https://c-ares.org/docs/ares_opt_param_t.html",
    "https://c-ares.org/docs/ares_parse_a_reply.html",
    "https://c-ares.org/docs/ares_parse_aaaa_reply.html",
    "https://c-ares.org/docs/ares_parse_caa_reply.html",
    "https://c-ares.org/docs/ares_parse_mx_reply.html",
    "https://c-ares.org/docs/ares_parse_naptr_reply.html",
    "https://c-ares.org/docs/ares_parse_ns_reply.html",
    "https://c-ares.org/docs/ares_parse_ptr_reply.html",
    "https://c-ares.org/docs/ares_parse_soa_reply.html",
    "https://c-ares.org/docs/ares_parse_srv_reply.html",
    "https://c-ares.org/docs/ares_parse_txt_reply.html",
    "https://c-ares.org/docs/ares_parse_uri_reply.html",
    "https://c-ares.org/docs/ares_process.html",
    "https://c-ares.org/docs/ares_process_fd.html",
    "https://c-ares.org/docs/ares_process_fds.html",
    "https://c-ares.org/docs/ares_process_pending_write.html",
    "https://c-ares.org/docs/ares_query.html",
    "https://c-ares.org/docs/ares_query_dnsrec.html",
    "https://c-ares.org/docs/ares_queue.html",
    "https://c-ares.org/docs/ares_queue_active_queries.html",
    "https://c-ares.org/docs/ares_queue_wait_empty.html",
    "https://c-ares.org/docs/ares_reinit.html",
    "https://c-ares.org/docs/ares_save_options.html",
    "https://c-ares.org/docs/ares_search.html",
    "https://c-ares.org/docs/ares_search_dnsrec.html",
    "https://c-ares.org/docs/ares_send.html",
    "https://c-ares.org/docs/ares_send_dnsrec.html",
    "https://c-ares.org/docs/ares_set_local_dev.html",
    "https://c-ares.org/docs/ares_set_local_ip4.html",
    "https://c-ares.org/docs/ares_set_local_ip6.html",
    "https://c-ares.org/docs/ares_set_pending_write_cb.html",
    "https://c-ares.org/docs/ares_set_server_state_callback.html",
    "https://c-ares.org/docs/ares_set_servers.html",
    "https://c-ares.org/docs/ares_set_servers_csv.html",
    "https://c-ares.org/docs/ares_set_servers_ports.html",
    "https://c-ares.org/docs/ares_set_servers_ports_csv.html",
    "https://c-ares.org/docs/ares_set_socket_callback.html",
    "https://c-ares.org/docs/ares_set_socket_configure_callback.html",
    "https://c-ares.org/docs/ares_set_socket_functions.html",
    "https://c-ares.org/docs/ares_set_socket_functions_ex.html",
    "https://c-ares.org/docs/ares_set_sortlist.html",
    "https://c-ares.org/docs/ares_strerror.html",
    "https://c-ares.org/docs/ares_svcb_param_t.html",
    "https://c-ares.org/docs/ares_threadsafety.html",
    "https://c-ares.org/docs/ares_timeout.html",
    "https://c-ares.org/docs/ares_tlsa_match_t.html",
    "https://c-ares.org/docs/ares_tlsa_selector_t.html",
    "https://c-ares.org/docs/ares_tlsa_usage_t.html",
    "https://c-ares.org/docs/ares_version.html",
]
document_has_api_usage = true
output_path = "database/c-ares/latest/out"
header_paths = ["database/c-ares/latest/code/include"]
driver_build_args = [
    "database/c-ares/latest/bin_asan/lib/libcares.a",
    "-Idatabase/c-ares/latest/build_asan",
]
consumer_case_paths = ["database/c-ares/latest/code/test"]
