
[zlib]

language = "c"

compile_commands_path = "database/zlib/latest/build_asan/compile_commands.json"


header_paths = ["database/zlib/latest/code/zlib.h", "database/zlib/latest/code/zconf.h"]


document_paths = ["database/zlib/latest/code/zlib.h"]


document_has_api_usage = true


output_path = "database/zlib/latest/out"


driver_build_args = [
    "database/zlib/latest/build_asan/libz.a",
    "-DHAVE_HIDDEN",
    "-DNO_FSEEKO",
    "-DZLIB_BUILD",
    "-DZLIB_DLL",
    "-D_LARGEFILE64_SOURCE=1"
]


consumer_case_paths = ["database/zlib/latest/code/examples", "database/zlib/latest/code/test"]


consumer_build_args = []


source_paths = []


exclude_paths = []


driver_headers = []


api_hints_path = ""

